import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
const outDir = path.join(repoRoot, "contracts", "out");
const generatedDir = path.join(repoRoot, "packages", "abis", "src", "generated");

const contracts = [
  "HubMoneyMarket",
  "HubRiskManager",
  "HubIntentInbox",
  "HubLockManager",
  "HubSettlement",
  "HubCustody",
  "TokenRegistry",
  "KinkInterestRateModel",
  "MockERC20",
  "MockOracle",
  "SpokePortal",
  "MockBridgeAdapter",
  "CanonicalBridgeAdapter",
  "MockCanonicalTokenBridge",
  "Verifier",
  "Groth16VerifierAdapter"
];

if (!fs.existsSync(outDir)) {
  throw new Error(`Foundry artifacts not found at ${outDir}. Run \`forge build\` first.`);
}

fs.mkdirSync(generatedDir, { recursive: true });

const exportsLines = [
  "// Auto-generated by packages/abis/scripts/generate.mjs",
  "export type Abi = readonly unknown[];"
];

for (const name of contracts) {
  const artifactPath = path.join(outDir, `${name}.sol`, `${name}.json`);
  if (!fs.existsSync(artifactPath)) {
    console.warn(`Skipping missing artifact ${artifactPath}`);
    continue;
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;
  const filePath = path.join(generatedDir, `${name}.json`);
  fs.writeFileSync(filePath, JSON.stringify(abi, null, 2));

  exportsLines.push(`import ${name}Json from \"./generated/${name}.json\";`);
  exportsLines.push(`export const ${name}Abi = ${name}Json as Abi;`);
}

fs.writeFileSync(path.join(repoRoot, "packages", "abis", "src", "index.ts"), `${exportsLines.join("\n")}\n`);
console.log("ABIs generated successfully");
